// ===================================================================
// Landsat 8/9 C2 L2 - day LST, NDVI, NDBI - 194 Colombo GN divisions
// Generated by src/step23a_make_climate_gee_js.py. Do not edit by hand;
// change the generator and re-run it.
//
// HOW TO RUN
//   1. https://code.earthengine.google.com
//   2. Paste this whole file, click Run
//   3. Check the console: scene counts per sensor, and the clear-observation
//      summary. A division with very few clear observations is a warning.
//   4. Tasks tab -> RUN on "gee_climate_vars"
//   5. Download from Drive/colombo_replication to
//      data/processed/gee_climate_vars.csv
//   6. python src/step24_screen_env9.py
//
// GEOMETRY: 1 km circular buffer around the division point, mean at 30 m -
// identical to the six existing environmental variables.
// ===================================================================

var BUFFER_M       = 1000;
var START          = '2023-01-01';
var END            = '2026-01-01';   // exclusive -> through 2025-12-31
var CLOUD_LAND_MAX = 40;             // scene filter, fixed in advance
var CRS            = 'EPSG:32644';   // UTM 44N, the Landsat grid here

// [Address, latitude, longitude] - from data/processed/gn_centroids.csv
var PTS = [
  ["athurugiriya", 6.86929800, 79.99728957],
  ["homagama", 6.85150529, 80.00212795],
  ["kolamunna", 6.79527339, 79.92260583],
  ["nugegoda", 6.87714931, 79.89036905],
  ["battaramulla", 6.89782702, 79.92191535],
  ["thalawathugoda", 6.87305802, 79.93800391],
  ["kottawa", 6.85088341, 79.96382549],
  ["malabe", 6.90603696, 79.96737749],
  ["moratuwella", 6.77116842, 79.88507943],
  ["dehiwala", 6.85753582, 79.86547701],
  ["boralesgamuwa", 6.83934214, 79.90232533],
  ["pannipitiya", 6.84797665, 79.94591912],
  ["thunadahena", 6.90360837, 79.98733798],
  ["pitakotte", 6.88829142, 79.90653097],
  ["maharagama", 6.84724374, 79.93210323],
  ["kaduwela", 6.93054644, 79.98704067],
  ["kothalawala", 6.92226174, 79.97987197],
  ["rajagiriya", 6.90675298, 79.89682484],
  ["habarakada", 6.87802513, 80.01768212],
  ["nawala", 6.89262546, 79.88893946],
  ["halpita", 6.77936569, 79.95622768],
  ["meegoda", 6.86078709, 80.05310155],
  ["diyagama", 6.80596250, 79.99738174],
  ["mount lavinia", 6.83924037, 79.86503484],
  ["mattegoda", 6.81439406, 79.96990528],
  ["padukka", 6.83868596, 80.09004645],
  ["kahathuduwa", 6.78338804, 79.99390737],
  ["pitipana", 6.82269857, 80.03054674],
  ["panagoda", 6.85835318, 80.02111210],
  ["kiriwattuduwa", 6.79626093, 80.00580742],
  ["hokandara", 6.87953488, 79.96903113],
  ["avissawella", 6.95410486, 80.21028619],
  ["nawagamuwa", 6.91358333, 80.01607493],
  ["havelock town", 6.88602640, 79.86628780],
  ["rukmale", 6.85624096, 79.97909835],
  ["rathmalana", 6.81149773, 79.87540606],
  ["kalalgoda", 6.86749995, 79.94964244],
  ["kesbewa", 6.78884869, 79.93605493],
  ["thalahena", 6.91319433, 79.95209242],
  ["koswatta", 6.89570145, 80.05128027],
  ["bokundara", 6.81714911, 79.92025995],
  ["kohuwala", 6.86389462, 79.88744986],
  ["makumbura", 6.83869284, 79.97614194],
  ["depanama", 6.85850622, 79.94775622],
  ["godagama", 6.84911562, 80.03189275],
  ["kalubovila", 6.86298671, 79.87753098],
  ["rattanapitiya", 6.84895269, 79.90142733],
  ["mirihana", 6.87899060, 79.90780810],
  ["rathmaldeniya", 6.83946376, 79.94994038],
  ["watareka", 6.85021644, 80.06686504],
  ["shanthalokagama", 6.89265656, 79.99684760],
  ["pepiliyana", 6.85701173, 79.88846110],
  ["vihara", 6.81950355, 79.86963369],
  ["wattegedara", 6.84736391, 79.91825177],
  ["welivita", 6.93603614, 79.95580880],
  ["belagama", 6.93508995, 79.92279666],
  ["beruketiya", 6.80056853, 80.05100801],
  ["borella", 6.91725323, 79.87977776],
  ["mahalwarawa", 6.83653129, 79.95588925],
  ["uyana", 6.78568606, 79.87875913],
  ["malapalla", 6.84780818, 79.98228744],
  ["arangala", 6.88605199, 79.96267386],
  ["pothuarawa", 6.89579602, 79.95253025],
  ["hanwella", 6.90421547, 80.08429718],
  ["polwatta", 6.85895601, 79.93896883],
  ["madiwela", 6.87772376, 79.92309656],
  ["subhoothipura", 6.90622318, 79.91414360],
  ["kalu aggala", 6.93051067, 80.10920739],
  ["boralugoda", 6.87398426, 79.98005110],
  ["ethulkotte", 6.89875380, 79.90634683],
  ["wellampitiya", 6.93939775, 79.89439850],
  ["atigala", 6.89596416, 80.06031833],
  ["rilawala", 6.79063910, 79.97904388],
  ["neelammahara", 6.83106430, 79.91878790],
  ["wellawatta", 6.87455640, 79.86178520],
  ["wijerama", 6.85363100, 79.90870898],
  ["bellanvila", 6.84791053, 79.88810459],
  ["henpita", 6.90404862, 80.05172556],
  ["katuwawala", 6.82852534, 79.91378666],
  ["thalapathpitiya", 6.86989382, 79.92231501],
  ["thumbovila", 6.81171983, 79.91185262],
  ["weniwelkola", 6.77096093, 79.98576674],
  ["pore", 6.88730549, 79.98451583],
  ["maradana", 6.92608146, 79.86418718],
  ["udahamulla", 6.86828110, 79.91610688],
  ["attidiya", 6.83075007, 79.88450854],
  ["gothatuwa", 6.92492498, 79.90746193],
  ["makuludoowa", 6.81358078, 79.93359938],
  ["mattakkuliya", 6.97217763, 79.87696217],
  ["navinna", 6.85503866, 79.91455693],
  ["pahalawela", 6.88487504, 79.92708929],
  ["pamunuwa", 6.85801032, 79.93224757],
  ["piriwena", 6.82530878, 79.87372094],
  ["kirulapone", 6.88048971, 79.87763326],
  ["kudamaduwa", 6.80119502, 79.95830708],
  ["nedimala", 6.85542518, 79.88048359],
  ["pathiragoda", 6.85693246, 79.92078756],
  ["thaldiyawala", 6.87144915, 79.98822188],
  ["himbutana", 6.92180463, 79.93536878],
  ["katubedda", 6.80042994, 79.89638094],
  ["kolonnawa", 6.93288220, 79.89688033],
  ["magammana", 6.82024625, 79.99757472],
  ["narahenpita", 6.90258829, 79.87825211],
  ["oruwala", 6.88392994, 80.00100874],
  ["dematagoda", 6.93581187, 79.87994957],
  ["divulpitiya", 6.85106299, 79.89436983],
  ["egodawatta", 6.84885651, 79.90793599],
  ["kosgama", 6.94419226, 80.13960468],
  ["madapatha", 6.76668986, 79.92919888],
  ["pahathgama", 6.89618509, 80.08363429],
  ["siyambalagoda", 6.79666533, 79.96933393],
  ["thalangama", 6.90886987, 79.93810851],
  ["walawwatta", 6.90105283, 80.07138167],
  ["dutugemunu", 6.86805343, 79.88169393],
  ["galavilawatta", 6.84021224, 79.99373130],
  ["grandpass", 6.94400595, 79.87458612],
  ["jambugasmulla", 6.86181871, 79.89566668],
  ["katuwana", 6.83466185, 80.00241841],
  ["malwatta", 6.85328052, 79.87069219],
  ["mullegama", 6.87898200, 80.01157898],
  ["mulleriyawa", 6.93743572, 79.92968080],
  ["ranala", 6.91656836, 80.03399107],
  ["watarappala", 6.84002254, 79.87077728],
  ["ambathale", 6.94137497, 79.93834770],
  ["kalapaluwawa", 6.91425134, 79.91272492],
  ["kaldemulla", 6.80644138, 79.87940684],
  ["kawdana", 6.84453249, 79.87687402],
  ["kirigampamunuwa", 6.80068897, 79.98046336],
  ["kotahena", 6.94917987, 79.86186225],
  ["kotikawatta", 6.93062533, 79.91724428],
  ["siddamulla", 6.81837708, 79.95858246],
  ["sri saranankara", 6.86869493, 79.86827574],
  ["uduwana", 6.82376988, 80.00764458],
  ["borupana", 6.81289158, 79.89182859],
  ["dampe", 6.79258467, 79.98359696],
  ["fort", 6.94405275, 79.83553270],
  ["gangodavila", 6.86310939, 79.90377505],
  ["henawatta", 6.85934155, 80.04040853],
  ["honnanthara", 6.79687336, 79.94858101],
  ["idama", 6.78002233, 79.88617437],
  ["kahapola", 6.75408994, 79.92485261],
  ["kajugahawatta", 6.92597194, 79.91074213],
  ["koralawella", 6.75835418, 79.88916693],
  ["kumaragewatta", 6.88927853, 79.94602080],
  ["kurunduwatta", 6.89399551, 79.90954236],
  ["madulawa", 6.82694801, 80.06628680],
  ["maligagodella", 6.92569183, 79.95129497],
  ["sedawatta", 6.95392539, 79.88418346],
  ["slave island", 6.92537015, 79.85039745],
  ["suwarapola", 6.79621439, 79.91411893],
  ["udumulla", 6.86760152, 80.02629512],
  ["wennawatta", 6.94241022, 79.90402890],
  ["wewala", 6.80090530, 79.90931340],
  ["wickramasinghapura", 6.88237871, 79.94174567],
  ["angampitiya", 6.84599907, 80.11902828],
  ["asiri uyana", 6.89500198, 79.92850500],
  ["bambalapitiya", 6.90250409, 79.85462752],
  ["batakettara", 6.78190955, 79.92447598],
  ["bomiriya", 6.93212327, 80.00077547],
  ["bopetta", 6.93268742, 79.90461865],
  ["dedigamuwa", 6.89740306, 80.02621052],
  ["diddeniya", 6.88511549, 80.10768240],
  ["galwala", 6.86127152, 79.86892845],
  ["ganegoda", 6.84448433, 80.10922560],
  ["gorakapitiya", 6.81429640, 79.94881282],
  ["hewagama", 6.93047742, 79.97705578],
  ["jalthara", 6.90172470, 80.04232665],
  ["karagampitiya", 6.84796022, 79.87160195],
  ["kelanimulla", 6.94514304, 79.92038015],
  ["kotuvila", 6.94941246, 79.89182628],
  ["lakshapathiya", 6.79716053, 79.88204044],
  ["liyanagoda", 6.85873726, 79.95915662],
  ["madampitiya", 6.96177771, 79.87549709],
  ["mahadeniya", 6.92570559, 79.96145725],
  ["mahawatta", 6.95746294, 79.87418643],
  ["maligakanda", 6.92864574, 79.86785123],
  ["mawathgama", 6.83326921, 80.01364811],
  ["modara", 6.96466116, 79.87173574],
  ["molpe", 6.79215218, 79.90103958],
  ["nawalamulla", 6.87178228, 80.04360154],
  ["neluwattuduwa", 6.89798848, 80.11582209],
  ["pagoda", 6.87782733, 79.89829698],
  ["paligedara", 6.81897291, 79.93275903],
  ["salamulla", 6.92687298, 79.89695620],
  ["seethawaka", 6.95425897, 80.21725718],
  ["thelawala", 6.80743696, 79.89375692],
  ["thummodara", 6.86409242, 80.16900070],
  ["thunnana", 6.88322945, 80.08540685],
  ["udyanaya", 6.85565213, 79.87560009],
  ["walpola", 6.91691655, 79.92269649],
  ["wedikanda", 6.82511408, 79.86546253],
  ["welipillewa", 6.88401738, 80.03150578],
  ["weragala", 6.82873481, 80.12020881],
  ["werahera", 6.82528313, 79.90448479]
];

// ---------------------------------------------------------------- geometry
var fc = ee.FeatureCollection(PTS.map(function (p) {
  return ee.Feature(ee.Geometry.Point([p[2], p[1]]).buffer(BUFFER_M),
                    {Address: p[0]});
}));
var aoi = fc.geometry().bounds();

// ---------------------------------------------------------------- Landsat
function sensor(id) {
  return ee.ImageCollection(id)
    .filterBounds(aoi)
    .filterDate(START, END)
    .filter(ee.Filter.lt('CLOUD_COVER_LAND', CLOUD_LAND_MAX));
}
var l8 = sensor('LANDSAT/LC08/C02/T1_L2');
var l9 = sensor('LANDSAT/LC09/C02/T1_L2');
print('Landsat 8 scenes', l8.size(), 'Landsat 9 scenes', l9.size());

function prep(img) {
  var qa = img.select('QA_PIXEL');
  var clear = qa.bitwiseAnd(1 << 0).eq(0)          // fill
      .and(qa.bitwiseAnd(1 << 1).eq(0))            // dilated cloud
      .and(qa.bitwiseAnd(1 << 2).eq(0))            // cirrus
      .and(qa.bitwiseAnd(1 << 3).eq(0))            // cloud
      .and(qa.bitwiseAnd(1 << 4).eq(0))            // cloud shadow
      .and(img.select('ST_B10').gt(0));            // ST fill
  var sr = img.select(['SR_B4', 'SR_B5', 'SR_B6'])
              .multiply(0.0000275).add(-0.2);
  var ndvi = sr.normalizedDifference(['SR_B5', 'SR_B4']).rename('ndvi');
  var ndbi = sr.normalizedDifference(['SR_B6', 'SR_B5']).rename('ndbi');
  var lst = img.select('ST_B10').multiply(0.00341802).add(149.0)
               .subtract(273.15).rename('lst_day_c');
  var water = qa.bitwiseAnd(1 << 7).neq(0).rename('water');
  return ndvi.addBands(ndbi).addBands(lst).addBands(water)
             .updateMask(clear).toFloat();
}

var coll = l8.merge(l9).map(prep);
var composite = coll.select(['ndvi', 'ndbi', 'lst_day_c']).median()
  .addBands(coll.select('water').median().rename('water_share'))
  .addBands(coll.select('ndvi').count().rename('clear_obs').toFloat());

// ---------------------------------------------------------------- extract
var out = composite.reduceRegions({
  collection: fc, reducer: ee.Reducer.mean(), scale: 30, crs: CRS
});
print('clear_obs across divisions',
      out.aggregate_stats('clear_obs'));
print('first rows', out.limit(5));

Export.table.toDrive({
  collection: out,
  description: 'gee_climate_vars',
  folder: 'colombo_replication',
  fileNamePrefix: 'gee_climate_vars',
  fileFormat: 'CSV',
  selectors: ['Address', 'lst_day_c', 'ndvi', 'ndbi', 'water_share',
              'clear_obs']
});
