"""Step 23a - generate the Earth Engine Code Editor script for three further
environmental and spatial variables: daytime land surface temperature, NDVI
and NDBI.

SAME GEOMETRY AS THE EXISTING SIX.  Every existing variable is the mean over a
1 km-radius circular buffer around the division point in
data/processed/gn_centroids.csv (step6a: the first gn_lat/gn_lon seen per
Address in listings_gn_clean.csv - the same point the amenity features were
computed from). Not a polygon mean. The 194 points are embedded in the emitted
script, as step6f / step6i do, so the extraction geometry cannot drift.

SOURCE.  Landsat 8 and 9, Collection 2, Tier 1, Level 2 (surface reflectance
and surface temperature), 30 m, acquisitions 2023-01-01 to 2025-12-31.

  scene filter     CLOUD_COVER_LAND < 40         fixed before any result seen
  pixel mask       QA_PIXEL bits 0-4 clear       fill, dilated cloud, cirrus,
                                                 cloud, cloud shadow
                   ST_B10 > 0                    surface temperature fill
  scaling          SR  x 0.0000275 - 0.2         USGS C2 L2 factors
                   ST  x 0.00341802 + 149.0 K    then - 273.15 -> deg C
  per scene        ndvi = (B5 - B4) / (B5 + B4)
                   ndbi = (B6 - B5) / (B6 + B5)
                   lst_day_c = ST_B10 in deg C   (~10:30 local overpass,
                                                  hence "day")
  composite        per-pixel MEDIAN over all clear observations
  reduction        mean over the 1 km buffer at 30 m in EPSG:32644

Two diagnostic columns are exported and NOT screened as candidates:
  water_share   share of the buffer whose median QA water flag is set - the
                coastal-buffer problem that inflates Fort's water_occurrence_pct
                applies to these layers too, and this column makes it visible
  clear_obs     mean number of clear observations per pixel in the buffer

The same pipeline is mirrored in Python by step23b (Planetary Computer COGs of
the identical USGS product) so the downstream steps are not blocked on an
Earth Engine login; step24 compares the two when both files exist.

Writes: scripts/gee_climate_vars.js
"""

import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CENTROIDS = os.path.join(ROOT, "data", "processed", "gn_centroids.csv")
OUT = os.path.join(ROOT, "scripts", "gee_climate_vars.js")

HEADER = """// ===================================================================
// Landsat 8/9 C2 L2 - day LST, NDVI, NDBI - 194 Colombo GN divisions
// Generated by src/step23a_make_climate_gee_js.py. Do not edit by hand;
// change the generator and re-run it.
//
// HOW TO RUN
//   1. https://code.earthengine.google.com
//   2. Paste this whole file, click Run
//   3. Check the console: scene counts per sensor, and the clear-observation
//      summary. A division with very few clear observations is a warning.
//   4. Tasks tab -> RUN on "gee_climate_vars"
//   5. Download from Drive/colombo_replication to
//      data/processed/gee_climate_vars.csv
//   6. python src/step24_screen_env9.py
//
// GEOMETRY: 1 km circular buffer around the division point, mean at 30 m -
// identical to the six existing environmental variables.
// ===================================================================

var BUFFER_M       = 1000;
var START          = '2023-01-01';
var END            = '2026-01-01';   // exclusive -> through 2025-12-31
var CLOUD_LAND_MAX = 40;             // scene filter, fixed in advance
var CRS            = 'EPSG:32644';   // UTM 44N, the Landsat grid here

// [Address, latitude, longitude] - from data/processed/gn_centroids.csv
var PTS = [
"""

FOOTER = """];

// ---------------------------------------------------------------- geometry
var fc = ee.FeatureCollection(PTS.map(function (p) {
  return ee.Feature(ee.Geometry.Point([p[2], p[1]]).buffer(BUFFER_M),
                    {Address: p[0]});
}));
var aoi = fc.geometry().bounds();

// ---------------------------------------------------------------- Landsat
function sensor(id) {
  return ee.ImageCollection(id)
    .filterBounds(aoi)
    .filterDate(START, END)
    .filter(ee.Filter.lt('CLOUD_COVER_LAND', CLOUD_LAND_MAX));
}
var l8 = sensor('LANDSAT/LC08/C02/T1_L2');
var l9 = sensor('LANDSAT/LC09/C02/T1_L2');
print('Landsat 8 scenes', l8.size(), 'Landsat 9 scenes', l9.size());

function prep(img) {
  var qa = img.select('QA_PIXEL');
  var clear = qa.bitwiseAnd(1 << 0).eq(0)          // fill
      .and(qa.bitwiseAnd(1 << 1).eq(0))            // dilated cloud
      .and(qa.bitwiseAnd(1 << 2).eq(0))            // cirrus
      .and(qa.bitwiseAnd(1 << 3).eq(0))            // cloud
      .and(qa.bitwiseAnd(1 << 4).eq(0))            // cloud shadow
      .and(img.select('ST_B10').gt(0));            // ST fill
  var sr = img.select(['SR_B4', 'SR_B5', 'SR_B6'])
              .multiply(0.0000275).add(-0.2);
  var ndvi = sr.normalizedDifference(['SR_B5', 'SR_B4']).rename('ndvi');
  var ndbi = sr.normalizedDifference(['SR_B6', 'SR_B5']).rename('ndbi');
  var lst = img.select('ST_B10').multiply(0.00341802).add(149.0)
               .subtract(273.15).rename('lst_day_c');
  var water = qa.bitwiseAnd(1 << 7).neq(0).rename('water');
  return ndvi.addBands(ndbi).addBands(lst).addBands(water)
             .updateMask(clear).toFloat();
}

var coll = l8.merge(l9).map(prep);
var composite = coll.select(['ndvi', 'ndbi', 'lst_day_c']).median()
  .addBands(coll.select('water').median().rename('water_share'))
  .addBands(coll.select('ndvi').count().rename('clear_obs').toFloat());

// ---------------------------------------------------------------- extract
var out = composite.reduceRegions({
  collection: fc, reducer: ee.Reducer.mean(), scale: 30, crs: CRS
});
print('clear_obs across divisions',
      out.aggregate_stats('clear_obs'));
print('first rows', out.limit(5));

Export.table.toDrive({
  collection: out,
  description: 'gee_climate_vars',
  folder: 'colombo_replication',
  fileNamePrefix: 'gee_climate_vars',
  fileFormat: 'CSV',
  selectors: ['Address', 'lst_day_c', 'ndvi', 'ndbi', 'water_share',
              'clear_obs']
});
"""


def main():
    with open(CENTROIDS, encoding="utf-8-sig") as fh:
        pts = list(csv.DictReader(fh))
    body = ",\n".join(f'  ["{p["Address"]}", {float(p["gn_lat"]):.8f}, '
                      f'{float(p["gn_lon"]):.8f}]' for p in pts)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER + body + "\n" + FOOTER)
    print(f"{len(pts)} divisions embedded")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
